services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - sleepr-mongo
  reservations:
    image: 843228159224.dkr.ecr.us-east-1.amazonaws.com/reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: 843228159224.dkr.ecr.us-east-1.amazonaws.com/auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: 843228159224.dkr.ecr.us-east-1.amazonaws.com/payments
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'
  notifications:
    image: 843228159224.dkr.ecr.us-east-1.amazonaws.com/notifications
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'
  sleepr-mongo:
    image: mongo
